hotkeys:
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-line:
    - ⌘-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  focus-all-tabs:
    - ⌘-⌥-Shift-I
  scroll-to-top:
    - Shift-PageUp
  scroll-page-up:
    - ⌥-PageUp
  scroll-up:
    - Ctrl-Shift-Up
  scroll-down:
    - Ctrl-Shift-Down
  scroll-page-down:
    - ⌥-PageDown
  scroll-to-bottom:
    - Shift-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - ⌘-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - ⌘-T
  toggle-window: []
  new-window:
    - ⌘-N
  profile: {}
  profile-selectors: {}
  group-selectors: {}
  toggle-fullscreen:
    - Ctrl+⌘+F
  close-tab:
    - ⌘-Shift-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - Ctrl-Tab
    - ⌘-Shift-]
  previous-tab:
    - Ctrl-Shift-Tab
    - ⌘-Shift-[
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  rearrange-panes:
    - Ctrl-Shift
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - ⌘-Shift-.
  combine-tabs:
    - ⌘-Shift-,
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-D
  split-bottom:
    - ⌘-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-W
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
  command-selector:
    - ⌘-Shift-P
terminal:
  frontend: xterm-webgl
  fontSize: 14
  fontWeight: 400
  fontWeightBold: 400
  fallbackFont: null
  linePadding: 1.2
  bell: 'off'
  bracketedPaste: true
  background: theme
  ligatures: false
  cursor: block
  cursorBlink: true
  hideTabIndex: false
  showTabProfileIcon: false
  hideCloseButton: false
  hideTabOptionsButton: false
  rightClick: menu
  pasteOnMiddleClick: true
  copyOnSelect: false
  copyAsHTML: true
  scrollOnInput: true
  altIsMeta: false
  wordSeparator: ' ()[]{}''"'
  colorScheme:
    name: custom
    foreground: '#d4d4d4'
    background: '#1e1e1e'
    cursor: '#bbbbbb'
    colors:
      - '#1e1e1e'
      - '#FF5647'
      - '#A5C261'
      - '#DCDCAA'
      - '#569CD6'
      - '#C586C0'
      - '#4EC9B0'
      - '#d4d4d4'
      - '#313131'
      - '#f58c80'
      - '#ddf88f'
      - '#eee5b2'
      - '#a5c7ff'
      - '#ddaaff'
      - '#b7fff9'
      - '#ffffff'
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  customColorSchemes:
    - name: custom
      foreground: '#d4d4d4'
      background: '#1e1e1e'
      cursor: '#bbbbbb'
      colors:
        - '#1e1e1e'
        - '#FF5647'
        - '#A5C261'
        - '#DCDCAA'
        - '#569CD6'
        - '#C586C0'
        - '#4EC9B0'
        - '#d4d4d4'
        - '#313131'
        - '#f58c80'
        - '#ddf88f'
        - '#eee5b2'
        - '#a5c7ff'
        - '#ddaaff'
        - '#b7fff9'
        - '#ffffff'
  warnOnMultilinePaste: false
  searchRegexAlwaysEnabled: false
  searchOptions:
    regex: false
    wholeWord: false
    caseSensitive: false
  detectProgress: true
  scrollbackLines: 30000
  drawBoldTextInBrightColors: true
  sixel: true
  minimumContrastRatio: 4
  trimWhitespaceOnPaste: true
  font: Consolas, Hack Nerd Font
  autoOpen: true
  useConPTY: true
  environment: {}
  setComSpec: false
  profile: local:binzsh
  showBuiltinProfiles: true
  showRecentProfiles: 3
  paneResizeStep: 0.1
  focusFollowsMouse: false
  identification: null
ssh:
  warnOnClose: false
  winSCPPath: null
  agentType: auto
  agentPath: null
  x11Display: null
  knownHosts: []
  verifyHostKeys: true
configSync:
  configID: null
  auto: false
  parts:
    hotkeys: true
    appearance: true
    vault: true
clickableLinks:
  modifier: null
docker:
  host: null
  port: null
  socket: null
accessibility:
  animations: true
appearance:
  dock: 'off'
  dockScreen: current
  dockFill: 0.5
  dockSpace: 1
  dockHideOnBlur: false
  dockAlwaysOnTop: true
  flexTabs: false
  tabsLocation: top
  tabsInFullscreen: false
  cycleTabs: true
  theme: Follow the color scheme
  frame: thin
  css: '/* * { color: blue !important; } */'
  opacity: 1
  vibrancy: false
  vibrancyType: blur
  lastTabClosesWindow: false
  spaciness: 1
  colorSchemeMode: dark
profiles: []
groups: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
recoverTabs: true
enableAnalytics: false
enableWelcomeTab: false
electronFlags:
  - - force_discrete_gpu
    - '0'
enableAutomaticUpdates: true
hideTray: false
version: 8
vault: null
encrypted: false
enableExperimentalFeatures: false
commandBlacklist: []
providerBlacklist: []
profileBlacklist: []
hacks:
  disableGPU: false
  disableVibrancyWhileDragging: false
  enableFluentBackground: false
language: en-US
defaultQuickConnectProvider: ssh
pluginBlacklist: []
