# --- copy mode ---
setw -g mode-keys vi

set -g set-clipboard on
set -g allow-passthrough on
unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi MouseDown1Pane select-pane \; send -X stop-selection \; send -X clear-selection

# --- extended keys ---
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# --- mouse ---
set -g mouse on
bind -T copy-mode-vi WheelUpPane   send -N2 -X scroll-up
bind -T copy-mode-vi WheelDownPane send -N2 -X scroll-down

# --- status bar ---
set -g status-left-length 30
set -g status-left '#{?client_prefix,#[bg=red bold][PREFIX]#[default],}[#S] '
set -g status-right ''

setw -g window-status-current-style 'bg=colour65,bold'

