#!/bin/bash

### if you use nodemanager
export SERVER_START_JAVA_VENDOR="Oracle"
export SERVER_START_ROOT_DIR="${DOMAIN_HOME}"

SERVER_START_ARGUMENTS="${SERVER_START_ARGUMENTS}"
export SERVER_START_ARGUMENTS

SERVER_START_CLASSPATH=""
if [ -n ${EXT_PRE_CLASSPATH} ]; then
    SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${EXT_PRE_CLASSPATH}"
fi
if [ -n ${CLASSPATH} ]; then
    SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${CLASSPATH}"
fi
if [ -n ${SERVER_START_CLASSPATH} ]; then
    SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${WL_HOME}/server/lib/weblogic_sp.jar"
    SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${WL_HOME}/server/lib/weblogic.jar"
else
    SERVER_START_CLASSPATH="${WL_HOME}/server/lib/weblogic_sp.jar;${WL_HOME}/server/lib/weblogic.jar"
fi
if [ -n ${EXT_POST_CLASSPATH} ]; then
    SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${EXT_POST_CLASSPATH}"
fi
export SERVER_START_CLASSPATH
