#!/bin/bash

### if you use nodemanager
export SERVER_START_JAVA_VENDOR="Oracle"
export SERVER_START_ROOT_DIR="${DOMAIN_HOME}"
export SERVER_START_ARGUMENTS="${ARGUMENTS}"
SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${EXT_PRE_CLASSPATH}"
SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${EXT_POST_CLASSPATH}"
SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${CLASSPATH}"
SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${WL_HOME}/server/lib/weblogic_sp.jar"
SERVER_START_CLASSPATH="${SERVER_START_CLASSPATH};${WL_HOME}/server/lib/weblogic.jar"
export SERVER_START_CLASSPATH
