FROM debezium/connect:2.7

USER root
RUN mkdir -p /usr/share/jmx-exporter/ && \
    chown -R kafka:kafka /usr/share/jmx-exporter/
USER kafka

COPY jmx_prometheus_javaagent-1.0.1.jar /usr/share/jmx-exporter/
COPY jmx-exporter/kafka_connect.yml /usr/share/jmx-exporter/

EXPOSE 8083 1234
