FROM bitnami/kafka:3.8

USER root
RUN mkdir -p /usr/share/jmx-exporter/ && \
    chown -R 1001:1001 /usr/share/jmx-exporter/
USER 1001

COPY jmx_prometheus_javaagent-0.20.0.jar /usr/share/jmx-exporter/
COPY jmx-exporter/kafka_broker.yml /usr/share/jmx-exporter/

EXPOSE 9091 9092 9093 9094 1234
