FROM bitnami/zookeeper:3.9

USER root
RUN mkdir -p /usr/share/prometheus && \
    chown -R 1001:1001 /usr/share/prometheus
USER 1001

COPY jmx_prometheus_javaagent-0.20.0.jar /usr/share/prometheus/jmx_prometheus_javaagent.jar
COPY jmx-exporter/zookeeper.yml /usr/share/prometheus/

EXPOSE 2181 2888 3888 1234
