FROM confluentinc/cp-kafka-connect:7.7.0

USER root
RUN mkdir -p /usr/share/jmx-exporter/ && \
    chown -R 1001:1001 /usr/share/jmx-exporter/
USER 1001

COPY jmx_prometheus_javaagent-1.0.1.jar /usr/share/jmx-exporter/
COPY jmx-exporter/kafka_connect.yml /usr/share/jmx-exporter/

EXPOSE 8083 1234
