FROM confluentinc/cp-schema-registry:7.7.0

USER root
RUN mkdir -p /usr/share/prometheus && \
    chown -R 1001:1001 /usr/share/prometheus
USER 1001

COPY jmx_prometheus_javaagent-0.20.0.jar /usr/share/prometheus/jmx_prometheus_javaagent.jar
COPY jmx-exporter/confluent_schemaregistry.yml /usr/share/prometheus/

EXPOSE 8081 1234
