#!/bin/bash
set -o errtrace
set -o errexit
trap 'echo "${BASH_SOURCE[0]}: line ${LINENO}: status ${?}: user ${USER}: func ${FUNCNAME[0]}"' ERR

CLUSTER_INSTANCE_NAME1="inst1"
CLUSTER_INSTANCE_NAME2="inst2"
CLUSTER_BIND_ADDRESS1="${BIND_ADDRESS}"
CLUSTER_BIND_ADDRESS2="${BIND_ADDRESS}"
PORT_OFFSET1="0"
PORT_OFFSET2="1"

JGROUPS_TCP_PORT="7600"
CLUSTER_TCP_PORT1="$(( ${JGROUPS_TCP_PORT} + ${PORT_OFFSET1} ))"
CLUSTER_TCP_PORT2="$(( ${JGROUPS_TCP_PORT} + ${PORT_OFFSET2} ))"
