#!/bin/bash

export COMPONENT_NAME="ohs1"
export COMPONENT_ADMIN_LISTEN_ADDRESS="127.0.0.1"
export COMPONENT_ADMIN_LISTEN_PORT="9999"
export COMPONENT_LISTEN_ADDRESS=""
export COMPONENT_LISTEN_PORT="7777"
export COMPONENT_SSL_LISTEN_PORT="4443"
